version: "3.7"
services:
  web:
    build:
      context: ./src/server
    image: flaskapp:latest
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./src/data
        target: /app/data
  # redis:
  #   image: redis:latest
  #   hostname: redis
  # worker:
  #   build:
  #     context: ./src/captioner
  #     dockerfile: Dockerfile
  #   command: ./scripts/run_celery.sh
  #   volumes:
  #     - type: bind
  #       source: ./src/data
  #       target: /app/data
  #   links:
  #     - redis
