version: "3.7"
services:
  web:
    build:
      context: ./src/server
    image: flaskapp:latest
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: data
        target: /data
